## Optimization

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
application_df.columns

Index(['EIN', 'NAME', 'APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION',
       'USE_CASE', 'ORGANIZATION', 'STATUS', 'INCOME_AMT',
       'SPECIAL_CONSIDERATIONS', 'ASK_AMT', 'IS_SUCCESSFUL'],
      dtype='object')

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(columns = ['EIN', 'NAME'], inplace=True)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
app_counts= application_df['APPLICATION_TYPE'].value_counts()
app_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_counts[app_counts<500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
class_binning = application_df['CLASSIFICATION'].value_counts()
class_binning

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_counts = class_binning[class_binning>1]
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

#Changed binning amount on classifications to 200

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`

classifications_to_replace = list(class_counts[class_counts<200].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1171
C7000      777
C1700      287
C1370        1
C1236        1
C2190        1
C4200        1
C5200        1
C6100        1
C2600        1
C1248        1
C1580        1
C1820        1
C1900        1
C2570        1
C1283        1
C3700        1
C2500        1
C1570        1
C2380        1
C1732        1
C1728        1
C2170        1
C4120        1
C8210        1
C4500        1
C1245        1
C2561        1
C2150        1
Name: CLASSIFICATION, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
app_dummies_df = pd.get_dummies(application_df)
app_dummies_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [11]:
# Split our preprocessed data into our features and target arrays
X = app_dummies_df.drop('IS_SUCCESSFUL', axis=1).values
y = app_dummies_df['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 78)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

##Added a layer and changed the node amounts

In [13]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
# Tried 80, 50, 30 for layers
input_features = X_train_scaled.shape[1]
hidden_nodes_layer1 = 20
hidden_nodes_layer2 = 30
hidden_nodes_layer3 = 50

# Create a neural network model
nn_model_1 = tf.keras.models.Sequential()

# First hidden layer
nn_model_1.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, activation='relu', input_dim=input_features))

# Second hidden layer
nn_model_1.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

#Added a third layer for optimization
# Third hidden layer
nn_model_1.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation='relu'))

# Output layer
nn_model_1.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn_model_1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 20)                1440

 dense_1 (Dense)             (None, 30)                630

 dense_2 (Dense)             (None, 50)                1550

 dense_3 (Dense)             (None, 1)                 51

=================================================================
Total params: 3,671
Trainable params: 3,671
Non-trainable params: 0
_________________________________________________________________

In [14]:
# Compile the model
nn_model_1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [16]:
# Create a callback that saves the model's weights every 5 epoch
import os
from tensorflow.keras.callbacks import ModelCheckpoint

# Define checkpoints variables
checkpoint_path= '../checkpoints/weights.{epoch}.hdf5'

cp_callback = ModelCheckpoint(filepath=checkpoint_path, verbose=2, save_weights_only=True, save_freq='epoch', period=5)

# Train the model
fit_model = nn_model_1.fit(X_train_scaled,y_train,epochs=100,callbacks=[cp_callback])

WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5820 - accuracy: 0.7111
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5540 - accuracy: 0.7291
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5511 - accuracy: 0.7308
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5501 - accuracy: 0.7317
Epoch 5/100
796/804 [============================>.] - ETA: 0s - loss: 0.5475 - accuracy: 0.7332
Epoch 5: saving model to ../checkpoints/weights.5.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5480 - accuracy: 0.7329
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5478 - accuracy: 0.7321
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7323
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7334
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7340
Epoch 10/100
781/804 [============================>.] - ETA: 0s - loss: 0.5452 - accuracy: 0.7340
Epoch 10: saving model to ../checkpoints/weights.10.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7342
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7350
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7344
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5439 - accuracy: 0.7356
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5433 - accuracy: 0.7359
Epoch 15/100
802/804 [============================>.] - ETA: 0s - loss: 0.5431 - accuracy: 0.7363
Epoch 15: saving model to ../checkpoints/weights.15.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7364
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7362
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7374
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7367
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7365
Epoch 20/100
792/804 [============================>.] - ETA: 0s - loss: 0.5413 - accuracy: 0.7376
Epoch 20: saving model to ../checkpoints/weights.20.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7373
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7377
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5412 - accuracy: 0.7372
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7373
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7381
Epoch 25/100
786/804 [============================>.] - ETA: 0s - loss: 0.5415 - accuracy: 0.7376
Epoch 25: saving model to ../checkpoints/weights.25.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7380
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7377
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7374
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7371
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7389
Epoch 30/100
788/804 [============================>.] - ETA: 0s - loss: 0.5398 - accuracy: 0.7376
Epoch 30: saving model to ../checkpoints/weights.30.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7374
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7395
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7380
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7384
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7387
Epoch 35/100
802/804 [============================>.] - ETA: 0s - loss: 0.5388 - accuracy: 0.7399
Epoch 35: saving model to ../checkpoints/weights.35.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7398
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7394
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7385
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7388
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5388 - accuracy: 0.7389
Epoch 40/100
777/804 [===========================>..] - ETA: 0s - loss: 0.5381 - accuracy: 0.7385
Epoch 40: saving model to ../checkpoints/weights.40.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7385
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7402
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7394
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7395
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7390
Epoch 45/100
796/804 [============================>.] - ETA: 0s - loss: 0.5370 - accuracy: 0.7397
Epoch 45: saving model to ../checkpoints/weights.45.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7393
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7390
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5376 - accuracy: 0.7392
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7393
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7393
Epoch 50/100
793/804 [============================>.] - ETA: 0s - loss: 0.5365 - accuracy: 0.7397
Epoch 50: saving model to ../checkpoints/weights.50.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7392
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7387
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5369 - accuracy: 0.7404
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7393
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7403
Epoch 55/100
790/804 [============================>.] - ETA: 0s - loss: 0.5361 - accuracy: 0.7401
Epoch 55: saving model to ../checkpoints/weights.55.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7401
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7396
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7398
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7407
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7401
Epoch 60/100
803/804 [============================>.] - ETA: 0s - loss: 0.5364 - accuracy: 0.7400
Epoch 60: saving model to ../checkpoints/weights.60.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7401
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7404
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7407
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7399
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5355 - accuracy: 0.7406
Epoch 65/100
803/804 [============================>.] - ETA: 0s - loss: 0.5360 - accuracy: 0.7403
Epoch 65: saving model to ../checkpoints/weights.65.hdf5
804/804 [==============================] - 3s 3ms/step - loss: 0.5361 - accuracy: 0.7402
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7404
Epoch 67/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7393
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7400
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7412
Epoch 70/100
779/804 [============================>.] - ETA: 0s - loss: 0.5340 - accuracy: 0.7405
Epoch 70: saving model to ../checkpoints/weights.70.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7398
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7410
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7403
Epoch 73/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7402
Epoch 74/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7408
Epoch 75/100
783/804 [============================>.] - ETA: 0s - loss: 0.5339 - accuracy: 0.7415
Epoch 75: saving model to ../checkpoints/weights.75.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7409
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7411
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7405
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7418
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7409
Epoch 80/100
779/804 [============================>.] - ETA: 0s - loss: 0.5350 - accuracy: 0.7407
Epoch 80: saving model to ../checkpoints/weights.80.hdf5
804/804 [==============================] - 2s 3ms/step - loss: 0.5346 - accuracy: 0.7411
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7415
Epoch 82/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7412
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7412
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7402
Epoch 85/100
795/804 [============================>.] - ETA: 0s - loss: 0.5336 - accuracy: 0.7426
Epoch 85: saving model to ../checkpoints/weights.85.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7419
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7411
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7410
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5341 - accuracy: 0.7413
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7404
Epoch 90/100
780/804 [============================>.] - ETA: 0s - loss: 0.5344 - accuracy: 0.7403
Epoch 90: saving model to ../checkpoints/weights.90.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7409
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7414
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5336 - accuracy: 0.7411
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7406
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7420
Epoch 95/100
778/804 [============================>.] - ETA: 0s - loss: 0.5350 - accuracy: 0.7409
Epoch 95: saving model to ../checkpoints/weights.95.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7409
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7412
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7415
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7413
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7413
Epoch 100/100
778/804 [============================>.] - ETA: 0s - loss: 0.5345 - accuracy: 0.7410
Epoch 100: saving model to ../checkpoints/weights.100.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7418

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model_1.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5579 - accuracy: 0.7277 - 462ms/epoch - 2ms/step
Loss: 0.5578625798225403, Accuracy: 0.7276967763900757

In [18]:
# Export our model to HDF5 file
from google.colab import files

nn_model_1.save('../h5/AlphabetSoupCharity_Optimization.h5')